import type { Metadata } from "next";
import "./globals.css";
import { Orbitron } from "next/font/google";
import { ThemeProvider } from "@/app/context/theme-context";
import Header from "@/components/header";
import Footer from "@/components/footer";

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["400", "900"],
  variable: "--font-orbitron",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en">
        <body className={`${orbitron.className} antialiased`}>
          <Header />
          {children}
          <Footer />
        </body>
      </html>
    </ThemeProvider>
  );
}
