export const teams = [
    {
      game: "Call of Duty",
      name: "Team Core",
      team: [
        {
          name: "Bhabishya Dhakal Chhetri",
          ign: "tcr-sexy.44",
          image: "/captain.png",
          role: "Player",
          igRole: "Captain",
          rank: "Diamond",
          level: 350,
        },
        {
          name: "John Doe",
          nickname: "JD",
          image: "/captain.png",
          role: "Admin",
          igRole: "Manager",
          breifResponsibility: "Managing team schedules",
        },
        {
          name: "Jane Smith",
          nickname: "tcr-ace.21",
          image: "/captain.png",
          role: "Admin",
          igRole: "Coach",
          breifResponsibility: "Coach team to be better players",
        },
        {
          name: "Alice Johnson",
          ign: "tcr-queen.99",
          image: "/captain.png",
          role: "Player",
          igRole: "Support",
          rank: "Gold",
          level: 250,
        },
        {
          name: "Bob Brown",
          ign: "tcr-king.77",
          image: "/captain.png",
          role: "Player",
          igRole: "Striker",
          rank: "Silver",
          level: 200,
        },
        {
          name: "Alice Johnson",
          ign: "tcr-queen.99",
          image: "/captain.png",
          role: "Player",
          igRole: "Support",
          rank: "Gold",
          level: 250,
        },
        {
          name: "Bob Brown",
          ign: "tcr-king.77",
          image: "/captain.png",
          role: "Player",
          igRole: "Striker",
          rank: "Silver",
          level: 200,
        },
        {
          name: "Alice Johnson",
          ign: "tcr-queen.99",
          image: "/captain.png",
          role: "Player",
          igRole: "Support",
          rank: "Gold",
          level: 250,
        },
      ],
    },
    {
      game: "Pub G",
      name: "Phoenix Core",
      team: [
        {
          name: "John Doe",
          nickname: "JD",
          image: "/captain.png",
          role: "Admin",
          igRole: "Manager",
          breifResponsibility: "Managing team schedules",
        },
        {
          name: "Jane Smith",
          nickname: "tcr-ace.21",
          image: "/captain.png",
          role: "Admin",
          igRole: "Coach",
          breifResponsibility: "Coach team to be better players",
        },
        {
          name: "Alice Johnson",
          ign: "tcr-queen.99",
          image: "/captain.png",
          role: "Player",
          igRole: "Support",
          rank: "Gold",
          level: 250,
        },
        {
          name: "Bob Brown",
          ign: "tcr-king.77",
          image: "/captain.png",
          role: "Player",
          igRole: "Striker",
          rank: "Silver",
          level: 200,
        },
        {
          name: "Alice Johnson",
          ign: "tcr-queen.99",
          image: "/captain.png",
          role: "Player",
          igRole: "Support",
          rank: "Gold",
          level: 250,
        },
        {
          name: "Bob Brown",
          ign: "tcr-king.77",
          image: "/captain.png",
          role: "Player",
          igRole: "Striker",
          rank: "Silver",
          level: 200,
        },
        {
          name: "Alice Johnson",
          ign: "tcr-queen.99",
          image: "/captain.png",
          role: "Player",
          igRole: "Support",
          rank: "Gold",
          level: 250,
        },
      ],
    },
  ];
  