export const teams = [
    {
      game: "Call of Duty",
      name: "Team Core",
      team: [
        {
          name: "Bhabishya Dhakal Chhetri",
          ign: "tcr-sexy.44",
          image: "/captain.png",
          role: "Player",
          igRole: "Captain",
          rank: "Diamond",
          level: 350,
        },
        {
          name: "John Doe",
          nickname: "JD",
          image: "/captain.png",
          role: "Admin",
          igRole: "Manager",
          breifResponsibility: "Managing team schedules",
        },
        {
          name: "Jane Smith",
          nickname: "tcr-ace.21",
          image: "/captain.png",
          role: "Admin",
          igRole: "Coach",
          breifResponsibility: "Coach team to be better players",
        },
        {
          name: "Alice Johnson",
          ign: "tcr-queen.99",
          image: "/captain.png",
          role: "Player",
          igRole: "Support",
          rank: "Gold",
          level: 250,
        },
        {
          name: "Bob Brown",
          ign: "tcr-king.77",
          image: "/captain.png",
          role: "Player",
          igRole: "Striker",
          rank: "Silver",
          level: 200,
        },
        {
          name: "Alice Johnson",
          ign: "tcr-queen.99",
          image: "/captain.png",
          role: "Player",
          igRole: "Support",
          rank: "Gold",
          level: 250,
        },
        {
          name: "Bob Brown",
          ign: "tcr-king.77",
          image: "/captain.png",
          role: "Player",
          igRole: "Striker",
          rank: "Silver",
          level: 200,
        },
        {
          name: "Alice Johnson",
          ign: "tcr-queen.99",
          image: "/captain.png",
          role: "Player",
          igRole: "Support",
          rank: "Gold",
          level: 250,
        },
      ],
    },
    {
      game: "Pub G",
      name: "Phoenix Core",
      team: [
        {
          name: "John Doe",
          nickname: "JD",
          image: "/captain.png",
          role: "Admin",
          igRole: "Manager",
          breifResponsibility: "Managing team schedules",
        },
        {
          name: "Jane Smith",
          nickname: "tcr-ace.21",
          image: "/captain.png",
          role: "Admin",
          igRole: "Coach",
          breifResponsibility: "Coach team to be better players",
        },
        {
          name: "Alice Johnson",
          ign: "tcr-queen.99",
          image: "/captain.png",
          role: "Player",
          igRole: "Support",
          rank: "Gold",
          level: 250,
        },
        {
          name: "Bob Brown",
          ign: "tcr-king.77",
          image: "/captain.png",
          role: "Player",
          igRole: "Striker",
          rank: "Silver",
          level: 200,
        },
        {
          name: "Alice Johnson",
          ign: "tcr-queen.99",
          image: "/captain.png",
          role: "Player",
          igRole: "Support",
          rank: "Gold",
          level: 250,
        },
      ],
    },
  ];
  
export const blogs = [
    {
      id: "12345-543-25637",
      title: "PUBG Mobile Pro League - South Asia Spring 2022",
      date: "17-12-2021",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. re et dolore magna aliqua. re et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. re et dolore magna aliqua. re et dolore magna aliqua. ",
      image: "/blog/active-blog.svg",
      link: "/blog",
    },
    {
      id: "12345-543-25612",
      title: "PUBG Mobile Club Open - Fall Split 2021: Nepal",
      date: "17-12-2021",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. re et dolore magna aliqua. re et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. re et dolore magna aliqua. re et dolore magna aliqua. ",
      image: "/blog/other-blog-1.png",
      link: "/blog/12345-543-25612",
    },
    {
      id: "12345-543-25154",
      title: "PUBG Mobile Club Open - Spring Split 2021: Nepal",
      date: "17-12-2021",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. re et dolore magna aliqua. re et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. re et dolore magna aliqua. re et dolore magna aliqua. ",
      image: "/blog/other-blog-2.png",
      link: "/blog/12345-543-25154",
    },
    {
      id: "12345-503-22354",
      title: "PUBG Mobile Pro League - South Asia Season 2",
      date: "17-12-2021",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. re et dolore magna aliqua. re et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. re et dolore magna aliqua. re et dolore magna aliqua. ",
      image: "/blog/other-blog-3.png",
      link: "/blog/12345-543-22354",
    },
    {
      id: "12345-513-25612",
      title: "PUBG Mobile Club Open - Fall Split 2021: Nepal",
      date: "17-12-2021",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. re et dolore magna aliqua. re et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. re et dolore magna aliqua. re et dolore magna aliqua. ",
      image: "/blog/other-blog-1.png",
      link: "/blog/12345-543-25612",
    },
    {
      id: "12345-533-25154",
      title: "PUBG Mobile Club Open - Spring Split 2021: Nepal",
      date: "17-12-2021",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. re et dolore magna aliqua. re et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. re et dolore magna aliqua. re et dolore magna aliqua. ",
      image: "/blog/other-blog-2.png",
      link: "/blog/12345-543-25154",
    },
    {
      id: "12345-523-22354",
      title: "PUBG Mobile Pro League - South Asia Season 2",
      date: "17-12-2021",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. re et dolore magna aliqua. re et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. re et dolore magna aliqua. re et dolore magna aliqua. ",
      image: "/blog/other-blog-3.png",
      link: "/blog/12345-543-22354",
    },
  ];